"""Basically does the encrypt and decrypt using basic XOR"""

from .lcg import LCG


class StreamCipher:
    """Stream Cipher using (LCG) for encryption and decryption."""

    def __init__(self, lcg: LCG):
        self.lcg = lcg

    def encrypt(self, plaintext: bytes) -> bytes:
        """Encrypt the plaintext using the keystream generated by LCG."""
        keystream = self.lcg.generate_keystream(len(plaintext))
        return bytes(p ^ k for p, k in zip(plaintext, keystream))

    def decrypt(self, ciphertext: bytes) -> bytes:
        """Decrypt the ciphertext using the keystream generated by LCG."""
        # NOTE: that XOR is symmetric
        return self.encrypt(ciphertext)
